import {
  Wind,
  Wrench,
  Droplets,
  Zap,
  Thermometer,
  Home,
  Building2,
  Layers,
  ShieldCheck,
  Tv,
  Paintbrush,
  Waves,
  Hammer,
  Grid3x3,
} from 'lucide-react'

export type ServiceColor = 'cyan' | 'purple' | 'magenta'

export const services = [
  {
    slug: 'ac-repair',
    label: 'AC Repair',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761506/ac_repair_d23fbs.png',
    description: 'Fast diagnosis and repair for all AC brands — gas refill, compressor, PCB, and full unit faults.',
    longDescription: 'Whether your AC is not cooling, making noise, leaking water, or not turning on at all — our certified technicians diagnose and fix it fast. We carry spare parts for all major brands including Daikin, Carrier, LG, Samsung, and Midea.',
    features: ['All major brands', 'Gas refill & leak fix', 'Compressor & PCB repair', 'Same-day service'],
    icon: Wind,
    color: 'cyan' as ServiceColor,
    metaTitle: 'AC Repair Dubai | Same-Day Service – Happy Brother Technical',
    metaDesc: 'Professional AC repair in Dubai for all brands. Gas refill, PCB, compressor repair. Same-day service available 24/7 across Dubai.',
  },
  {
    slug: 'ac-installation',
    label: 'AC Installation',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761504/ac_installation_rzk95l.png',
    description: 'Professional installation of split, ducted, and cassette AC units to DEWA standards.',
    longDescription: 'We install all types of air conditioning units including split, ducted, cassette, and window ACs. All work is done to DEWA compliance standards with proper piping, wiring, vacuuming, and gas charging.',
    features: ['All unit types', 'Piping & wiring', 'Vacuuming & gas charge', 'Performance testing'],
    icon: Thermometer,
    color: 'purple' as ServiceColor,
    metaTitle: 'AC Installation Dubai | DEWA Compliant – Happy Brother Technical',
    metaDesc: 'Expert AC installation in Dubai for split, ducted & cassette units. DEWA compliant, all brands, 24/7 availability.',
  },
  {
    slug: 'ac-maintenance',
    label: 'AC Maintenance',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/v1776761504/ac_maintenance_cp9y3j.png',
    description: 'Annual and periodic AC servicing to keep your unit efficient and prevent breakdowns.',
    longDescription: 'Regular maintenance extends AC lifespan and prevents costly breakdowns. Our AMC (Annual Maintenance Contract) packages cover scheduled visits, coil cleaning, filter washing, and gas pressure checks.',
    features: ['Deep coil cleaning', 'Filter wash', 'Gas pressure check', 'AMC contracts'],
    icon: ShieldCheck,
    color: 'magenta' as ServiceColor,
    metaTitle: 'AC Maintenance Dubai | AMC Contracts – Happy Brother Technical',
    metaDesc: 'Scheduled AC maintenance and AMC contracts in Dubai. Coil cleaning, filter wash, gas checks. Prevent breakdowns before they happen.',
  },
  {
    slug: 'plumbing',
    label: 'Plumbing',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761503/plumbing_work_e4ykc5.png',
    description: 'Complete plumbing solutions — leaks, drain blockages, tap replacement, and water pressure.',
    longDescription: 'From minor drips to major pipe bursts, our licensed plumbers handle all residential and commercial plumbing in Dubai. Emergency service available round the clock.',
    features: ['Leak detection', 'Drain unblocking', 'Tap & fixture fitting', 'Emergency service'],
    icon: Droplets,
    color: 'cyan' as ServiceColor,
    metaTitle: 'Plumber Dubai | 24/7 Emergency Plumbing – Happy Brother Technical',
    metaDesc: 'Licensed plumbers in Dubai for leaks, drains, tap repair and water pressure issues. 24/7 emergency plumbing service.',
  },
  {
    slug: 'electrical-work',
    label: 'Electrical Work',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761504/electrical_work_wpndds.png',
    description: 'Certified DEWA-compliant electrical work — wiring, sockets, breakers, and lighting.',
    longDescription: 'All our electrical work is carried out by DEWA-certified electricians. We handle everything from socket fittings to full rewiring and distribution board upgrades.',
    features: ['Socket & switch fitting', 'DB board upgrades', 'Fault finding', 'Light installation'],
    icon: Zap,
    color: 'purple' as ServiceColor,
    metaTitle: 'Electrician Dubai | DEWA Certified – Happy Brother Technical',
    metaDesc: 'DEWA-certified electricians in Dubai for wiring, sockets, DB boards, and lighting. Safe, compliant, and affordable.',
  },
  {
    slug: 'painting',
    label: 'Painting',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761500/Paintnig_Services_vcl8yu.png',
    description: 'Interior and exterior painting with proper surface prep for homes and offices.',
    longDescription: 'Transform your space with professional painting. We handle surface prep, crack filling, priming, and apply quality paints for a lasting finish — from single rooms to entire villas.',
    features: ['Interior & exterior', 'Crack filling & priming', 'Texture finishes', 'Villa to single room'],
    icon: Paintbrush,
    color: 'magenta' as ServiceColor,
    metaTitle: 'Painting Services Dubai | Interior & Exterior – Happy Brother Technical',
    metaDesc: 'Professional painting in Dubai for homes and offices. Interior, exterior, texture finishes. Proper prep for a lasting result.',
  },
  {
    slug: 'carpentry',
    label: 'Carpentry',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761505/car_pantary_work_logp4a.png',
    description: 'Custom carpentry — furniture assembly, built-in wardrobes, cabinets, and partitions.',
    longDescription: 'Our experienced carpenters handle everything from IKEA assembly to fully custom built-in wardrobes, kitchen cabinets, and wooden partitions tailored to your space.',
    features: ['IKEA assembly', 'Built-in wardrobes', 'Custom cabinets', 'Wooden partitions'],
    icon: Hammer,
    color: 'cyan' as ServiceColor,
    metaTitle: 'Carpenter Dubai | Custom Carpentry – Happy Brother Technical',
    metaDesc: 'Expert carpentry in Dubai — IKEA assembly, built-in wardrobes, cabinets, and wooden partitions. Quality craftsmanship guaranteed.',
  },
  {
    slug: 'tiling',
    label: 'Tiling',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761503/tiling_jx4sqm.png',
    description: 'Floor and wall tiling — new installation, tile replacement, grouting, and polishing.',
    longDescription: 'Whether you need a full floor re-tile or a single cracked tile replaced, our tiling specialists work with ceramic, porcelain, marble, and all natural stones.',
    features: ['Ceramic, porcelain, marble', 'Single tile replacement', 'Re-grouting', 'Tile polishing'],
    icon: Grid3x3,
    color: 'purple' as ServiceColor,
    metaTitle: 'Tiling Dubai | Floor & Wall Tiles – Happy Brother Technical',
    metaDesc: 'Professional tiling in Dubai for floors and walls. New installation, single tile replacement, grouting and polishing.',
  },
  {
    slug: 'handyman',
    label: 'Handyman',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761503/handyman_services_xws2s4.png',
    description: 'All-in-one handyman for small repairs, furniture assembly, curtain rods, and home fixes.',
    longDescription: 'Got a list of small jobs around the house? Our handyman service covers everything — hanging pictures, fixing doors, patching walls, assembling furniture, and more.',
    features: ['Picture & curtain hanging', 'Door & lock repair', 'Wall patching', 'Shelf fitting'],
    icon: Wrench,
    color: 'magenta' as ServiceColor,
    metaTitle: 'Handyman Dubai | Home Repairs & Fixes – Happy Brother Technical',
    metaDesc: 'Reliable handyman service in Dubai for small repairs, furniture assembly, curtain hanging, wall patching and more.',
  },
  {
    slug: 'deep-cleaning',
    label: 'Deep Cleaning',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761502/deeep_cleaning_xcsqqe.png',
    description: 'Professional deep cleaning for apartments, villas, and offices including post-renovation.',
    longDescription: 'Our deep cleaning service goes beyond regular cleaning — we degrease kitchens, sanitize bathrooms, clean inside appliances, and handle post-renovation dust removal for a truly fresh start.',
    features: ['Kitchen degreasing', 'Bathroom sanitization', 'Inside appliances', 'Move-in/out clean'],
    icon: Home,
    color: 'cyan' as ServiceColor,
    metaTitle: 'Deep Cleaning Dubai | Apartments, Villas & Offices – Happy Brother Technical',
    metaDesc: 'Professional deep cleaning in Dubai for homes and offices. Kitchen, bathroom, move-in/out cleaning. Book today.',
  },
  {
    slug: 'door-repair',
    label: 'Door Repair',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761500/door_repairing_anfm44.png',
    description: 'Repair and replacement of all door types — hinges, locks, alignments, and auto doors.',
    longDescription: 'Sticking doors, broken locks, faulty hinges, or misaligned frames — we fix all door types including wooden, aluminium, and automatic sliding doors.',
    features: ['Door alignment', 'Lock replacement', 'Hinge & closer fix', 'Automatic doors'],
    icon: Building2,
    color: 'purple' as ServiceColor,
    metaTitle: 'Door Repair Dubai | All Door Types – Happy Brother Technical',
    metaDesc: 'Professional door repair in Dubai for wooden, aluminium, and automatic doors. Hinges, locks, alignment and closers fixed fast.',
  },
  {
    slug: 'gypsum-false-ceiling',
    label: 'Gypsum False Ceiling',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761500/gypsum_false_ceiling_mjfaet.png',
    description: 'Gypsum board and POP false ceiling installation with cove lighting and AC grille cutouts.',
    longDescription: 'Upgrade your interiors with a professionally installed gypsum or POP false ceiling. We handle the full job — framing, boarding, cove lighting, AC grille cutouts, and a smooth skim coat finish.',
    features: ['Gypsum & POP ceilings', 'Cove & recessed lighting', 'Cornice work', 'Repairs & patching'],
    icon: Layers,
    color: 'magenta' as ServiceColor,
    metaTitle: 'Gypsum False Ceiling Dubai | POP & Cove Lighting – Happy Brother Technical',
    metaDesc: 'Expert gypsum false ceiling installation in Dubai. POP ceilings, cove lighting, cornice work, and repairs.',
  },
  {
    slug: 'tv-mounting',
    label: 'TV Mounting',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761500/tv_mounting_jptx7g.png',
    description: 'Safe TV wall mounting on any surface with clean cable management and soundbar fitting.',
    longDescription: 'We safely mount TVs of all sizes on any wall surface — concrete, gypsum, brick, or tiled. All cables are neatly concealed and soundbar brackets are fitted if needed.',
    features: ['All wall types', 'All TV sizes', 'Cable concealment', 'Soundbar mounting'],
    icon: Tv,
    color: 'cyan' as ServiceColor,
    metaTitle: 'TV Mounting Dubai | All Wall Types – Happy Brother Technical',
    metaDesc: 'Professional TV wall mounting in Dubai. All TV sizes, all wall types, clean cable management. Fast and affordable.',
  },
  {
    slug: 'water-heater-repair',
    label: 'Water Heater Repair',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761500/Water_heater_repairing_z0aud8.png',
    description: 'Repair and replacement of electric and gas water heaters — element, thermostat, and tank.',
    longDescription: 'No hot water? Our technicians repair electric and gas water heaters quickly — element replacements, thermostat faults, anode rod replacement, and full unit swaps when needed.',
    features: ['Electric & gas heaters', 'Thermostat repair', 'Element replacement', 'Full unit replacement'],
    icon: Thermometer,
    color: 'purple' as ServiceColor,
    metaTitle: 'Water Heater Repair Dubai | Electric & Gas – Happy Brother Technical',
    metaDesc: 'Fast water heater repair in Dubai for electric and gas units. Thermostat, element, and full replacement service.',
  },
  {
    slug: 'waterproofing',
    label: 'Waterproofing',
    image: 'https://res.cloudinary.com/dyqn6xgfn/image/upload/f_auto,q_auto/v1776761500/water_proofing_kiwxmh.png',
    description: 'Waterproofing for bathrooms, rooftops, balconies, and basements with warranty.',
    longDescription: 'Stop leaks before they cause costly damage. Our waterproofing solutions cover bathrooms, wet rooms, rooftops, balconies, and basements — using membrane, injection, or coating systems with warranty.',
    features: ['Bathroom & wet rooms', 'Rooftop membrane', 'Crack injection', 'Leak source detection'],
    icon: Waves,
    color: 'magenta' as ServiceColor,
    metaTitle: 'Waterproofing Dubai | Rooftop, Bathroom & Balcony – Happy Brother Technical',
    metaDesc: 'Professional waterproofing in Dubai for bathrooms, rooftops, and balconies. Membrane, injection, and coating systems with warranty.',
  },
]

export type Service = (typeof services)[0]